repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy src/robotocore/ --ignore-missing-imports
        language: system
        pass_filenames: false
        types_or: [python]
      - id: bandit
        name: bandit
        entry: uv run bandit -r src/robotocore/ -ll -c pyproject.toml -q
        language: system
        pass_filenames: false
        types_or: [python]
