#!/usr/bin/env python3
"""Generate CRUD lifecycle tests for AWS services.

For each service + resource noun, generates tests that exercise:
  Create → Describe → List → Delete → Describe(expect 404)

Usage:
    uv run python scripts/gen_lifecycle_tests.py --service s3
    uv run python scripts/gen_lifecycle_tests.py --service dynamodb --write
    uv run python scripts/gen_lifecycle_tests.py --service sqs --dry-run
    uv run python scripts/gen_lifecycle_tests.py --service ec2 \
        --file tests/compatibility/test_ec2_lifecycle.py
"""

import argparse
import sys
from pathlib import Path

import botocore.session

from scripts.chunk_service import extract_noun

# Map verb prefixes to CRUD categories
CRUD_VERBS = {
    "create": ("Create", "Put", "Add", "Register"),
    "read": ("Describe", "Get", "List"),
    "update": ("Update", "Modify", "Put"),
    "delete": ("Delete", "Remove", "Deregister"),
}


def _to_snake_case(name: str) -> str:
    import re

    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _classify_op(op_name: str) -> str | None:
    """Classify an operation into CRUD category."""
    for category, prefixes in CRUD_VERBS.items():
        for prefix in prefixes:
            if op_name.startswith(prefix):
                return category
    return None


def find_lifecycle_groups(service_name: str) -> list[dict]:
    """Find resource groups with enough CRUD ops for lifecycle testing."""
    session = botocore.session.get_session()
    try:
        model = session.get_service_model(service_name)
    except Exception:
        return []

    # Group ops by resource noun
    groups: dict[str, dict[str, list[str]]] = {}
    for op_name in model.operation_names:
        noun = extract_noun(op_name)
        category = _classify_op(op_name)
        if category:
            groups.setdefault(noun, {}).setdefault(category, []).append(op_name)

    # Filter to groups that have at least create + read (or delete)
    lifecycle_groups = []
    for noun, categories in sorted(groups.items()):
        has_create = bool(categories.get("create"))
        has_read = bool(categories.get("read"))
        has_delete = bool(categories.get("delete"))

        if has_create and (has_read or has_delete):
            lifecycle_groups.append(
                {
                    "noun": noun,
                    "create": categories.get("create", []),
                    "read": categories.get("read", []),
                    "update": categories.get("update", []),
                    "delete": categories.get("delete", []),
                    "completeness": sum([has_create, has_read, has_delete]),
                }
            )

    # Sort by completeness (most complete first)
    lifecycle_groups.sort(key=lambda g: -g["completeness"])
    return lifecycle_groups


def generate_test_code(service_name: str, groups: list[dict]) -> str:
    """Generate Python test code for lifecycle tests."""
    lines = [
        f'"""CRUD lifecycle tests for {service_name}.',
        "",
        "Auto-generated by scripts/gen_lifecycle_tests.py",
        "Tests the Create → Describe → List → Delete → Describe(404) lifecycle.",
        '"""',
        "",
        "import uuid",
        "",
        "import pytest",
        "from botocore.exceptions import ClientError",
        "",
        "from tests.compatibility.conftest import make_client",
        "",
        "",
        "@pytest.fixture",
        "def client():",
        f'    return make_client("{service_name}")',
        "",
    ]

    for group in groups:
        noun = group["noun"]
        noun_snake = _to_snake_case(noun)

        create_op = group["create"][0] if group["create"] else None
        read_ops = group["read"]
        delete_op = group["delete"][0] if group["delete"] else None

        # Find a describe/get op (prefer Describe over Get over List)
        describe_op = None
        list_op = None
        for op in read_ops:
            if op.startswith("Describe"):
                describe_op = op
            elif op.startswith("Get") and not describe_op:
                describe_op = op
            elif op.startswith("List"):
                list_op = op

        if not create_op:
            continue

        lines.append("")
        lines.append(f"class Test{noun}Lifecycle:")
        lines.append(f'    """Create → Read → Delete lifecycle for {noun}."""')
        lines.append("")

        # Generate lifecycle test
        lines.append(f"    def test_{noun_snake}_lifecycle(self, client):")
        lines.append(f'        """Full CRUD lifecycle for {noun}."""')
        lines.append("        unique = uuid.uuid4().hex[:8]")
        lines.append("")
        lines.append(f"        # TODO: Fill in {create_op} params for {service_name}")
        lines.append("        # create_params = {}")
        lines.append(f"        # response = client.{_to_snake_case(create_op)}(**create_params)")
        lines.append("        # assert response['ResponseMetadata']['HTTPStatusCode'] == 200")

        if describe_op:
            lines.append("")
            lines.append(f"        # Verify resource exists via {describe_op}")
            lines.append(f"        # describe_response = client.{_to_snake_case(describe_op)}(...)")
            lines.append("        # assert describe_response is not None")

        if list_op:
            lines.append("")
            lines.append(f"        # Verify resource appears in {list_op}")
            lines.append(f"        # list_response = client.{_to_snake_case(list_op)}()")
            lines.append("        # assert len(list_response[...]) >= 1")

        if delete_op:
            lines.append("")
            lines.append(f"        # Clean up via {delete_op}")
            lines.append(f"        # client.{_to_snake_case(delete_op)}(...)")

            if describe_op:
                lines.append("")
                lines.append("        # Verify resource is gone")
                lines.append("        # with pytest.raises(ClientError) as exc_info:")
                lines.append(f"        #     client.{_to_snake_case(describe_op)}(...)")
                lines.append(
                    "        # assert exc_info.value.response"
                    "['ResponseMetadata']['HTTPStatusCode'] in (400, 404)"
                )

        lines.append("        pass  # TODO: implement")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate CRUD lifecycle tests")
    parser.add_argument("--service", required=True, help="AWS service name")
    parser.add_argument("--write", action="store_true", help="Write test file")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be generated")
    parser.add_argument("--file", help="Output file path")
    args = parser.parse_args()

    groups = find_lifecycle_groups(args.service)

    if not groups:
        print(f"No lifecycle-testable resource groups found for {args.service}")
        return 1

    if args.dry_run or not args.write:
        print(f"\n{args.service}: {len(groups)} lifecycle-testable resource groups")
        print()
        for g in groups:
            ops = []
            if g["create"]:
                ops.append(f"C:{g['create'][0]}")
            if g["read"]:
                ops.append(f"R:{g['read'][0]}")
            if g["update"]:
                ops.append(f"U:{g['update'][0]}")
            if g["delete"]:
                ops.append(f"D:{g['delete'][0]}")
            print(f"  {g['noun']:30s} {' → '.join(ops)}")

        if not args.write:
            print("\nUse --write to generate test file.")
            return 0

    code = generate_test_code(args.service, groups)
    service_snake = args.service.replace("-", "_")
    output_path = args.file or f"tests/compatibility/test_{service_snake}_lifecycle.py"
    path = Path(output_path)

    if args.write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code)
        print(f"Wrote {path} ({len(groups)} lifecycle groups)")
    else:
        print(code)

    return 0


if __name__ == "__main__":
    sys.exit(main())
