"""Endpoint configuration generators for IaC tools targeting robotocore."""

from __future__ import annotations

from pathlib import Path

# Terraform services that need explicit endpoint overrides.
# Covers all 38 native + commonly-used Moto-backed services.
_TF_SERVICE_ENDPOINTS = [
    "acm",
    "apigateway",
    "apigatewayv2",
    "appconfig",
    "appsync",
    "athena",
    "autoscaling",
    "batch",
    "cloudformation",
    "cloudfront",
    "cloudwatch",
    "cloudwatchlogs",
    "codecommit",
    "codepipeline",
    "cognitoidp",
    "configservice",
    "dynamodb",
    "ec2",
    "ecr",
    "ecs",
    "efs",
    "elasticache",
    "elasticsearch",
    "elb",
    "elbv2",
    "emr",
    "events",
    "firehose",
    "glacier",
    "glue",
    "iam",
    "iot",
    "kafka",
    "kinesis",
    "kms",
    "lambda",
    "mediastore",
    "mq",
    "neptune",
    "opensearch",
    "organizations",
    "qldb",
    "rds",
    "redshift",
    "resourcegroups",
    "resourcegroupstaggingapi",
    "route53",
    "route53resolver",
    "s3",
    "sagemaker",
    "scheduler",
    "secretsmanager",
    "ses",
    "sesv2",
    "sfn",
    "sns",
    "sqs",
    "ssm",
    "sts",
    "swf",
    "timestreamwrite",
    "transcribe",
    "waf",
    "wafv2",
    "xray",
]


def generate_terraform_provider_override(directory: Path, endpoint_url: str) -> Path:
    """Write a ``provider_override.tf`` that points all AWS services at *endpoint_url*.

    Returns the path to the generated file.
    """
    endpoints_block = "\n".join(
        f'    {svc} = "{endpoint_url}"' for svc in sorted(_TF_SERVICE_ENDPOINTS)
    )

    content = f"""\
# Auto-generated by robotocore IaC test scaffold — do not edit.
provider "aws" {{
  access_key                  = "testing"
  secret_key                  = "testing"
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {{
{endpoints_block}
  }}
}}
"""
    path = directory / "provider_override.tf"
    path.write_text(content)
    return path


def get_aws_env_vars(endpoint_url: str) -> dict:
    """Return a dict of env vars for tools that honour ``AWS_ENDPOINT_URL``."""
    return {
        "AWS_ACCESS_KEY_ID": "testing",
        "AWS_SECRET_ACCESS_KEY": "testing",
        "AWS_DEFAULT_REGION": "us-east-1",
        "AWS_ENDPOINT_URL": endpoint_url,
    }


def generate_pulumi_config(directory: Path, endpoint_url: str) -> Path:
    """Write a ``Pulumi.test.yaml`` stack config with endpoint overrides.

    Returns the path to the generated file.
    """
    content = f"""\
# Auto-generated by robotocore IaC test scaffold — do not edit.
config:
  aws:accessKey: testing
  aws:secretKey: testing
  aws:region: us-east-1
  aws:skipCredentialsValidation: "true"
  aws:skipMetadataApiCheck: "true"
  aws:skipRequestingAccountId: "true"
  aws:s3UsePathStyle: "true"
  aws:endpoints:
    - s3: "{endpoint_url}"
      sts: "{endpoint_url}"
      iam: "{endpoint_url}"
      lambda: "{endpoint_url}"
      dynamodb: "{endpoint_url}"
      sqs: "{endpoint_url}"
      sns: "{endpoint_url}"
      cloudformation: "{endpoint_url}"
      cloudwatch: "{endpoint_url}"
      ec2: "{endpoint_url}"
      kinesis: "{endpoint_url}"
      route53: "{endpoint_url}"
      apigateway: "{endpoint_url}"
      ssm: "{endpoint_url}"
      secretsmanager: "{endpoint_url}"
"""
    path = directory / "Pulumi.test.yaml"
    path.write_text(content)
    return path
